### ISSUE TITLE
Where is the intro/exercises directory?

### ISSUE THREAD

**Issue by ritchieanesco** [kentcdodds/learn-react-hooks#1]
I'm looking through the README and in the **Working Through It** section it states:

> You'll want to start in the intro/exercises directory where we start with raw React and DOM APIs. Pull open the .html files in your browser and follow along in the comments. 

I can't seem to find this folder. Did my setup not work correctly?

**Comment by kentcdodds** [comment]
Whoops! Thanks for mentioning that. This was a copy/paste mistake which I just fixed :)

**Comment by kentcdodds** [comment]
👏 Thank you for working through the pre-workshop material!
