### ISSUE TITLE
useRef in 02.extra-4.js

### ISSUE THREAD

**Issue by CharlieStras** [kentcdodds/learn-react-hooks#23]
Hi, I'm wondering what does `useRef` do in this case.

https://github.com/kentcdodds/learn-react-hooks/blob/10c79048b915b27df13a04a2a81ccbf2a6b7bcab/src/final/02.extra-4.js#L20

**Comment by kentcdodds** [comment]
Hi @CharlieStras!

The `useRef` here allows us to store the `key` value in a place that's associated with the component in a way that won't trigger re-renders when the value is updated.

I plan to write a blog post about `useRef` eventually.

**Comment by mojjy** [comment]
Hi @kentcdodds 
I also have a question regarding this,
doesn't the ref get updated before we call the effect code, so we never end up removing the item?

**Comment by kentcdodds** [comment]
The ref gets initialized here: https://github.com/kentcdodds/react-hooks/blob/10c79048b915b27df13a04a2a81ccbf2a6b7bcab/src/final/02.extra-4.js#L20

But after initialization, React ignores the `key` value.

So the update happens here: https://github.com/kentcdodds/react-hooks/blob/10c79048b915b27df13a04a2a81ccbf2a6b7bcab/src/final/02.extra-4.js#L27

That runs *after* our comparison. So we will remove the item :)
